package:
  name:    smtk
  version: "master{{ environ['DATECODE'] }}"

build:
  script_env:
    - DATECODE
    - CONDA_BUILD_SYSROOT

source:
  - folder: moab
    git_rev: '6425a480ffe8e08b96453618fc5530e08e68ae8a'
    git_url: https://bitbucket.org/fathomteam/moab.git

  - folder: smtk
    git_rev: master
    git_url: https://gitlab.kitware.com/cmb/smtk.git

requirements:
  host:
    - python
    - boost=1.66.0
    - eigen
    - hdf5
    - libnetcdf
    - nlohmann_json
  build:
    - python
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - git
    - make
    - pybind11
  run:
    - boost=1.66.0
    - eigen
    - hdf5
    - netcdf4
    - nlohmann_json
    - python

outputs:
  - name: smtk
    files:
      - include/smtk
      - lib/*iMesh*
      - lib/libcJSON.*
      - lib/libMOAB.*
      - lib/cmake
      - lib/libsmtk*
      - lib/python{{PY_VER}}/site-packages/smtk

test:
  imports:
    - smtk
    - smtk.attribute
    - smtk.common
    - smtk.io
    - smtk.mesh
    - smtk.model
    - smtk.operation
    - smtk.resource
    - smtk.session.mesh
    - smtk.session.polygon
    - smtk.simulation
    - smtk.view

about:
  home:          https://gitlab.kitware.com/cmb/smtk
  license:       BSD
  license_file:  smtk/LICENSE.txt
